"""Add step_summary_system_prompt to User model

Revision ID: 07a86302fb43
Revises: f51ad2aecb5a
Create Date: 2025-07-07 15:29:03.802876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a86302fb43'
down_revision = 'f51ad2aecb5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch_alter_table for better compatibility, especially with SQLite.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step_summary_system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('step_summary_system_prompt')
    # ### end Alembic commands ###