"""Initial migration with all tables

Revision ID: 7e3a160bf346
Revises: 
Create Date: 2025-07-04 09:34:09.476413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3a160bf346'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('llm_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('openai_api_key', sa.String(length=255), nullable=True),
    sa.Column('anthropic_api_key', sa.String(length=255), nullable=True),
    sa.Column('google_api_key', sa.String(length=255), nullable=True),
    sa.Column('ollama_base_url', sa.String(length=255), nullable=True),
    sa.Column('apollo_client_id', sa.String(length=255), nullable=True),
    sa.Column('apollo_client_secret', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('process_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bi_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('step_description', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('vision_statement', sa.Text(), nullable=True),
    sa.Column('in_scope', sa.Text(), nullable=True),
    sa.Column('out_of_scope', sa.Text(), nullable=True),
    sa.Column('interfaces_text', sa.Text(), nullable=True),
    sa.Column('what_is_actually_done', sa.Text(), nullable=True),
    sa.Column('pain_points', sa.Text(), nullable=True),
    sa.Column('targets_text', sa.Text(), nullable=True),
    sa.Column('llm_comment_1', sa.Text(), nullable=True),
    sa.Column('llm_comment_2', sa.Text(), nullable=True),
    sa.Column('llm_comment_3', sa.Text(), nullable=True),
    sa.Column('llm_comment_4', sa.Text(), nullable=True),
    sa.Column('llm_comment_5', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bi_id')
    )
    op.create_table('process_step_process_step_relevance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_process_step_id', sa.Integer(), nullable=False),
    sa.Column('target_process_step_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('relevance_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 100', name='relevance_ps_ps_score_check'),
    sa.CheckConstraint('source_process_step_id != target_process_step_id', name='no_self_step_relevance'),
    sa.ForeignKeyConstraint(['source_process_step_id'], ['process_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_process_step_id'], ['process_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_process_step_id', 'target_process_step_id', name='unique_process_step_process_step_relevance')
    )
    op.create_table('use_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bi_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('process_step_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('inspiration', sa.Text(), nullable=True),
    sa.Column('wave', sa.String(length=255), nullable=True),
    sa.Column('effort_level', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('business_problem_solved', sa.Text(), nullable=True),
    sa.Column('target_solution_description', sa.Text(), nullable=True),
    sa.Column('technologies_text', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('relevants_text', sa.Text(), nullable=True),
    sa.Column('reduction_time_transfer', sa.String(length=255), nullable=True),
    sa.Column('reduction_time_launches', sa.String(length=255), nullable=True),
    sa.Column('reduction_costs_supply', sa.String(length=255), nullable=True),
    sa.Column('quality_improvement_quant', sa.String(length=255), nullable=True),
    sa.Column('ideation_notes', sa.Text(), nullable=True),
    sa.Column('further_ideas', sa.Text(), nullable=True),
    sa.Column('effort_quantification', sa.Text(), nullable=True),
    sa.Column('potential_quantification', sa.Text(), nullable=True),
    sa.Column('dependencies_text', sa.Text(), nullable=True),
    sa.Column('contact_persons_text', sa.Text(), nullable=True),
    sa.Column('related_projects_text', sa.Text(), nullable=True),
    sa.Column('pilot_site_factory_text', sa.Text(), nullable=True),
    sa.Column('usecase_type_category', sa.String(length=255), nullable=True),
    sa.Column('llm_comment_1', sa.Text(), nullable=True),
    sa.Column('llm_comment_2', sa.Text(), nullable=True),
    sa.Column('llm_comment_3', sa.Text(), nullable=True),
    sa.Column('llm_comment_4', sa.Text(), nullable=True),
    sa.Column('llm_comment_5', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('priority IS NULL OR (priority >= 1 AND priority <= 4)', name='priority_range_check'),
    sa.ForeignKeyConstraint(['process_step_id'], ['process_steps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bi_id')
    )
    op.create_table('usecase_area_relevance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_usecase_id', sa.Integer(), nullable=False),
    sa.Column('target_area_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('relevance_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 100', name='relevance_score_check'),
    sa.ForeignKeyConstraint(['source_usecase_id'], ['use_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_usecase_id', 'target_area_id', name='unique_usecase_area_relevance')
    )
    op.create_table('usecase_step_relevance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_usecase_id', sa.Integer(), nullable=False),
    sa.Column('target_process_step_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('relevance_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 100', name='relevance_step_score_check'),
    sa.ForeignKeyConstraint(['source_usecase_id'], ['use_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_process_step_id'], ['process_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_usecase_id', 'target_process_step_id', name='unique_usecase_step_relevance')
    )
    op.create_table('usecase_usecase_relevance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_usecase_id', sa.Integer(), nullable=False),
    sa.Column('target_usecase_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('relevance_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 100', name='relevance_uc_score_check'),
    sa.CheckConstraint('source_usecase_id != target_usecase_id', name='no_self_relevance'),
    sa.ForeignKeyConstraint(['source_usecase_id'], ['use_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_usecase_id'], ['use_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_usecase_id', 'target_usecase_id', name='unique_usecase_usecase_relevance')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usecase_usecase_relevance')
    op.drop_table('usecase_step_relevance')
    op.drop_table('usecase_area_relevance')
    op.drop_table('use_cases')
    op.drop_table('process_step_process_step_relevance')
    op.drop_table('process_steps')
    op.drop_table('llm_settings')
    op.drop_table('users')
    op.drop_table('areas')
    # ### end Alembic commands ###
